name: Ivugurura API CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the develop branch
  push:
    branches:
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.20.4]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages and run tests
        run: |
          yarn
          yarn test
        env:
          CI: true

  deploy:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH and deploy the app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/ivugururaApi
            echo "Refleshing SSH keys..."
            eval $(ssh-agent);
            ssh-add;
            ssh-add ${{ secrets.KEY_NAME }};
            git reset --hard
            git checkout develop
            git pull origin develop
            yarn install --production=true
            echo "Restart the server"
            yarn migrate
            yarn build-stating
            pm2 restart 1
